language: node_js

matrix:
    include:
        - os: linux
          dist: precise
          language: android
          sudo: required
          android:
            components:
              # Uncomment the lines below if you want to
              # use the latest revision of Android SDK Tools
              - platform-tools
              - tools

              # The BuildTools version used by your project
              - build-tools-25.0.0

              # The SDK version used to compile your project
              - android-25

              # Additional components
              - extra-google-m2repository
              - extra-android-m2repository

              # Specify at least one system image,
              # if you need to run emulator(s) during your tests
              - sys-img-x86-android-24
              - sys-img-armeabi-v7a-android-24
          script:
            - echo y | android update sdk -u --filter android-24
            # Launch Android emulator
            #- echo no | android create avd --force -n test -t android-21 --abi x86
            - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
            - emulator -avd test -no-audio -no-window &
            - android-wait-for-emulator
            - travis_wait 30 npm run test-platform -- 'android'
        - os: osx
          language: objective-c
          osx_image: xcode8
          before_install:
            - brew install couchdb
            - brew services start couchdb
          script:
            - travis_wait 30 npm run test-platform -- 'ios'

before_script:
    # Update npm
    - npm update -g npm
    # Run setup to replicate animaldb
    - ./setup.rb
    - nvm install 6
    - npm install
    # for now only check javascript production source files follow guidelines.
    - npm run lint

before_install:
    - jdk_switcher use oraclejdk8
